### ISSUE TITLE
BotKube official helm chart?

### ISSUE THREAD

**Issue by pierluigilenoci** [ebrianne/helm-charts#20]
Hello,
I don't understand what the official chart is.

On the [BotKube repo there is one](https://github.com/infracloudio/botkube/tree/develop/helm/botkube) and this one is on [artifacthub](https://artifacthub.io/packages/helm/ebrianne/botkube) (not updated with the latest versions).

**Comment by ebrianne** [comment]
Hi,

The official chart is the one on the botkube repo. I have just added a couple of things (communication secret to avoid unencrypted values) and plan to integrate them into the botkube official chart when I have some time.

**Comment by pierluigilenoci** [comment]
Please do a PR asap because the "existingSecret" issue is a big deal! Thanks.

**Comment by ebrianne** [comment]
Will be deprecated to due PR infracloudio/botkube#482 once this is put into the "official" helm chart
