### ISSUE TITLE
Botkube chart update to the latest version available

### ISSUE THREAD

**Issue by pierluigilenoci** [ebrianne/helm-charts#22]
Ref: https://github.com/infracloudio/botkube/releases/tag/v0.12.2

**Comment by pierluigilenoci** [comment]
@ebrianne could you please take a look?

**Comment by pierluigilenoci** [comment]
@ebrianne could you please take a look?

**Comment by ebrianne** [comment]
I ll update this when I have some time

**Comment by ebrianne** [comment]
I have updated the chart with the two latest tags #24 and #25

**Comment by pierluigilenoci** [comment]
@ebrianne thank you a lot!!! ❤️ 

Thank you so much for your efforts, they are really appreciated. 🙏🏻 🥇

**Comment by pierluigilenoci** [comment]
Hi @ebrianne I had a problem with the new chart version.
Ref: https://github.com/ebrianne/helm-charts/commit/1fed4481ad00bf4313a95e8a91a410763b94ba21#r56132019
