### ISSUE TITLE
[local-path-provisioner] Not public archive chart

### ISSUE THREAD

**Issue by ymrsmns** [ebrianne/helm-charts#23]
Hi 

Need to create release local-path-provisioner-0.0.20 
MR #21 

Can`t download the latest version 

 curl https://github.com/ebrianne/helm-charts/releases/download/local-path-provisioner-0.0.20/local-path-provisioner-0.0.20.tgz
HTTP/2 404
Not Found

**Comment by ebrianne** [comment]
It has been fixed
